### PR TITLE
Add support for targetting Python 3.10

### PR DESCRIPTION
**Pull request by lxop**
Fixes: #32

### CODE REVIEW

**Review by lensvol — APPROVED** [review]
Looks good!

**Comment by lxop** [comment]
Thanks @lensvol . Any chance of a merge?

**Comment by lensvol** [comment]
Yep, needed to verify few things first. :)

Thank you!

**Comment by lxop** [comment]
Thanks @lensvol ; do you have a plan to cut a new release anytime soon? It would be good to get this support into the IDE

**Comment by lensvol** [comment]
I plan to do either a small patch-level release really soon, or a full-blown minor release around Christmas.

**Pull request merged**
