### PR TITLE
(🎁) Update project to be more inline with the template

### PR DESCRIPTION
**Pull request by KotlinIsland**
This PR makes many changes to the Gradle configuration and Github actions, importing a lot of changes from the [intellij platform plugin template](https://github.com/JetBrains/intellij-platform-plugin-template)

It simplifies the changelog and automates the release process with a rolling draft release and automated publish.

It also adds [plugin signing](https://github.com/JetBrains/intellij-platform-plugin-template#plugin-signing), so that will need to be configured in the projects secrets if that's what you want to go with. [see this](https://github.com/JetBrains/intellij-platform-plugin-template#environment-variables)

The message about your cat was very touching, a similar thing happened to our cat last year 😞.

### CODE REVIEW

**Comment by lensvol** [comment]
Thank you! I will look it over in a couple of days.

**Comment by KotlinIsland** [comment]
@lensvol if you could approve workflows I could continue working on it now.

Alternatively I could enable workflows on my fork.

**Comment by KotlinIsland** [comment]
```
me.lensvol.blackconnect.BlackdClientTestCase > test_windows_newlines_are_replaced_in_blackd_response FAILED
    java.lang.NullPointerException at BlackdClientTestCase.kt:40

me.lensvol.blackconnect.BlackdClientTestCase > test_unix_newlines_in_blackd_response_are_left_as_is FAILED
    java.lang.NullPointerException at BlackdClientTestCase.kt:64

me.lensvol.blackconnect.SmokeTestCase > test_whole_file_is_reformatted_via_menu_action FAILED
    com.intellij.testFramework.TestLogger$TestLoggerAssertionError at SmokeTestCase.kt:45
        Caused by: java.lang.NullPointerException at BlackdClient.kt:118
```
image

**Comment by lensvol** [comment]
Please explain your last comment?

**Comment by KotlinIsland** [comment]
Oh sorry, it's just failed test in the ci and I need to investigate further, currently I'm just like, hmmm 😕

**Comment by KotlinIsland** [comment]
This is good now, just codecov complaining.

**Comment by KotlinIsland** [comment]
@lensvol There was an issue with your recent refactor of the version check, `"".parseInt()` throws an `Exception`, so I've fixed that here.

**Comment by KotlinIsland** [comment]
I agree, it's just that it was making the tests fail in this branch.

**Comment by lensvol** [comment]
I understand, but that should go away as soon as the PR with the fix gets merged.

**Comment by KotlinIsland** [comment]
Okay, I'll remove it. likely there is an issue with this branch that is causing the version header to not appear during test time.

**Pull request closed without merging**
